//#line 2 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the uvc_cam package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __uvc_cam__UVCCAMCONFIG_H__
#define __uvc_cam__UVCCAMCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace uvc_cam
{
  class UVCCamConfigStatics;
  
  class UVCCamConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(UVCCamConfig &config, const UVCCamConfig &max, const UVCCamConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const UVCCamConfig &config1, const UVCCamConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, UVCCamConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const UVCCamConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, UVCCamConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const UVCCamConfig &config) const = 0;
      virtual void getValue(const UVCCamConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T UVCCamConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (UVCCamConfig::* field);

      virtual void clamp(UVCCamConfig &config, const UVCCamConfig &max, const UVCCamConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const UVCCamConfig &config1, const UVCCamConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, UVCCamConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const UVCCamConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, UVCCamConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const UVCCamConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const UVCCamConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, UVCCamConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, UVCCamConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<UVCCamConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(UVCCamConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("camera_name"==(*i)->name){camera_name = boost::any_cast<std::string>(val);}
        if("device"==(*i)->name){device = boost::any_cast<std::string>(val);}
        if("format_mode"==(*i)->name){format_mode = boost::any_cast<int>(val);}
        if("width"==(*i)->name){width = boost::any_cast<int>(val);}
        if("height"==(*i)->name){height = boost::any_cast<int>(val);}
        if("frame_id"==(*i)->name){frame_id = boost::any_cast<std::string>(val);}
        if("frame_rate"==(*i)->name){frame_rate = boost::any_cast<double>(val);}
        if("camera_info_url"==(*i)->name){camera_info_url = boost::any_cast<std::string>(val);}
        if("absolute_exposure"==(*i)->name){absolute_exposure = boost::any_cast<int>(val);}
        if("exposure"==(*i)->name){exposure = boost::any_cast<int>(val);}
        if("sharpness"==(*i)->name){sharpness = boost::any_cast<int>(val);}
        if("power_line_frequency"==(*i)->name){power_line_frequency = boost::any_cast<int>(val);}
        if("white_balance_temperature"==(*i)->name){white_balance_temperature = boost::any_cast<bool>(val);}
        if("gain"==(*i)->name){gain = boost::any_cast<int>(val);}
        if("saturation"==(*i)->name){saturation = boost::any_cast<int>(val);}
        if("contrast"==(*i)->name){contrast = boost::any_cast<int>(val);}
        if("brightness"==(*i)->name){brightness = boost::any_cast<int>(val);}
      }
    }

    std::string camera_name;
std::string device;
int format_mode;
int width;
int height;
std::string frame_id;
double frame_rate;
std::string camera_info_url;
int absolute_exposure;
int exposure;
int sharpness;
int power_line_frequency;
bool white_balance_temperature;
int gain;
int saturation;
int contrast;
int brightness;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      std::string camera_name;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      std::string device;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int format_mode;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int width;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int height;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      std::string frame_id;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double frame_rate;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      std::string camera_info_url;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int absolute_exposure;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int exposure;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int sharpness;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int power_line_frequency;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool white_balance_temperature;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int gain;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int saturation;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int contrast;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int brightness;
//#line 255 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("UVCCamConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const UVCCamConfig &__max__ = __getMax__();
      const UVCCamConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const UVCCamConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const UVCCamConfig &__getDefault__();
    static const UVCCamConfig &__getMax__();
    static const UVCCamConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const UVCCamConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void UVCCamConfig::ParamDescription<std::string>::clamp(UVCCamConfig &config, const UVCCamConfig &max, const UVCCamConfig &min) const
  {
    return;
  }

  class UVCCamConfigStatics
  {
    friend class UVCCamConfig;
    
    UVCCamConfigStatics()
    {
UVCCamConfig::GroupDescription<UVCCamConfig::DEFAULT, UVCCamConfig> Default("Default", "", 0, 0, true, &UVCCamConfig::groups);
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.camera_name = "";
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.camera_name = "";
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.camera_name = "camera";
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<std::string>("camera_name", "str", 3, "The name of the camera (serial number or otherwise)", "", &UVCCamConfig::camera_name)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<std::string>("camera_name", "str", 3, "The name of the camera (serial number or otherwise)", "", &UVCCamConfig::camera_name)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.device = "";
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.device = "";
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.device = "/dev/video0";
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<std::string>("device", "str", 3, "The v4l2 device path", "", &UVCCamConfig::device)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<std::string>("device", "str", 3, "The v4l2 device path", "", &UVCCamConfig::device)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.format_mode = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.format_mode = 3;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.format_mode = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("format_mode", "int", 3, "The format the camera should be captured in", "{'enum_description': 'The camera capture format', 'enum': [{'srcline': 44, 'description': 'Capture in RGB mode', 'srcfile': '../cfg/UVCCam.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'MODE_RGB'}, {'srcline': 45, 'description': 'Capture in YUYV mode', 'srcfile': '../cfg/UVCCam.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'MODE_YUYV'}, {'srcline': 46, 'description': 'Capture in MJPG mode', 'srcfile': '../cfg/UVCCam.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'MODE_MJPEG'}]}", &UVCCamConfig::format_mode)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("format_mode", "int", 3, "The format the camera should be captured in", "{'enum_description': 'The camera capture format', 'enum': [{'srcline': 44, 'description': 'Capture in RGB mode', 'srcfile': '../cfg/UVCCam.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'MODE_RGB'}, {'srcline': 45, 'description': 'Capture in YUYV mode', 'srcfile': '../cfg/UVCCam.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'MODE_YUYV'}, {'srcline': 46, 'description': 'Capture in MJPG mode', 'srcfile': '../cfg/UVCCam.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'MODE_MJPEG'}]}", &UVCCamConfig::format_mode)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.width = -2147483648;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.width = 2147483647;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.width = 640;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("width", "int", 3, "Width of image in pixels.", "", &UVCCamConfig::width)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("width", "int", 3, "Width of image in pixels.", "", &UVCCamConfig::width)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.height = -2147483648;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.height = 2147483647;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.height = 480;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("height", "int", 3, "Height of image in pixels.", "", &UVCCamConfig::height)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("height", "int", 3, "Height of image in pixels.", "", &UVCCamConfig::height)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.frame_id = "";
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.frame_id = "";
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.frame_id = "camera";
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<std::string>("frame_id", "str", 3, "ROS tf frame of reference, resolved with tf_prefix unless absolute.", "", &UVCCamConfig::frame_id)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<std::string>("frame_id", "str", 3, "ROS tf frame of reference, resolved with tf_prefix unless absolute.", "", &UVCCamConfig::frame_id)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.frame_rate = 1.875;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.frame_rate = 240.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.frame_rate = 15.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<double>("frame_rate", "double", 3, "Camera speed (frames per second).", "", &UVCCamConfig::frame_rate)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<double>("frame_rate", "double", 3, "Camera speed (frames per second).", "", &UVCCamConfig::frame_rate)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.camera_info_url = "";
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.camera_info_url = "";
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.camera_info_url = "";
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<std::string>("camera_info_url", "str", 0, "Camera calibration URL for this video_mode (uncalibrated if null).", "", &UVCCamConfig::camera_info_url)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<std::string>("camera_info_url", "str", 0, "Camera calibration URL for this video_mode (uncalibrated if null).", "", &UVCCamConfig::camera_info_url)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.absolute_exposure = -2147483648;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.absolute_exposure = 2147483647;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.absolute_exposure = 2089;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("absolute_exposure", "int", 0, "absolute exposure of the camera", "", &UVCCamConfig::absolute_exposure)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("absolute_exposure", "int", 0, "absolute exposure of the camera", "", &UVCCamConfig::absolute_exposure)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.exposure = -2147483648;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.exposure = 2147483647;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.exposure = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("exposure", "int", 0, "menu selection for the exposure mode of the camera", "", &UVCCamConfig::exposure)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("exposure", "int", 0, "menu selection for the exposure mode of the camera", "", &UVCCamConfig::exposure)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.sharpness = -2147483648;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.sharpness = 2147483647;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.sharpness = 142;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("sharpness", "int", 0, "sharpness of the camera image", "", &UVCCamConfig::sharpness)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("sharpness", "int", 0, "sharpness of the camera image", "", &UVCCamConfig::sharpness)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.power_line_frequency = -2147483648;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.power_line_frequency = 2147483647;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.power_line_frequency = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("power_line_frequency", "int", 0, "menu selection for the power line frequency", "", &UVCCamConfig::power_line_frequency)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("power_line_frequency", "int", 0, "menu selection for the power line frequency", "", &UVCCamConfig::power_line_frequency)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.white_balance_temperature = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.white_balance_temperature = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.white_balance_temperature = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<bool>("white_balance_temperature", "bool", 0, "white balance of the camera", "", &UVCCamConfig::white_balance_temperature)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<bool>("white_balance_temperature", "bool", 0, "white balance of the camera", "", &UVCCamConfig::white_balance_temperature)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gain = -2147483648;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gain = 2147483647;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gain = 82;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("gain", "int", 0, "gain of the camera", "", &UVCCamConfig::gain)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("gain", "int", 0, "gain of the camera", "", &UVCCamConfig::gain)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.saturation = -2147483648;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.saturation = 2147483647;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.saturation = 50;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("saturation", "int", 0, "saturation of the camera", "", &UVCCamConfig::saturation)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("saturation", "int", 0, "saturation of the camera", "", &UVCCamConfig::saturation)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.contrast = -2147483648;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.contrast = 2147483647;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.contrast = 50;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("contrast", "int", 0, "contrast of the camera", "", &UVCCamConfig::contrast)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("contrast", "int", 0, "contrast of the camera", "", &UVCCamConfig::contrast)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.brightness = -2147483648;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.brightness = 2147483647;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.brightness = 66;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("brightness", "int", 0, "brightness of the camera", "", &UVCCamConfig::brightness)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UVCCamConfig::AbstractParamDescriptionConstPtr(new UVCCamConfig::ParamDescription<int>("brightness", "int", 0, "brightness of the camera", "", &UVCCamConfig::brightness)));
//#line 233 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(UVCCamConfig::AbstractGroupDescriptionConstPtr(new UVCCamConfig::GroupDescription<UVCCamConfig::DEFAULT, UVCCamConfig>(Default)));
//#line 390 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<UVCCamConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<UVCCamConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<UVCCamConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    UVCCamConfig __max__;
    UVCCamConfig __min__;
    UVCCamConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const UVCCamConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static UVCCamConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &UVCCamConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const UVCCamConfig &UVCCamConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const UVCCamConfig &UVCCamConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const UVCCamConfig &UVCCamConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<UVCCamConfig::AbstractParamDescriptionConstPtr> &UVCCamConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<UVCCamConfig::AbstractGroupDescriptionConstPtr> &UVCCamConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const UVCCamConfigStatics *UVCCamConfig::__get_statics__()
  {
    const static UVCCamConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = UVCCamConfigStatics::get_instance();
    
    return statics;
  }

//#line 44 "../cfg/UVCCam.cfg"
      const int UVCCam_MODE_RGB = 1;
//#line 45 "../cfg/UVCCam.cfg"
      const int UVCCam_MODE_YUYV = 2;
//#line 46 "../cfg/UVCCam.cfg"
      const int UVCCam_MODE_MJPEG = 3;
}

#endif // __UVCCAMRECONFIGURATOR_H__
